#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rails-deprecated_sanitizer
Version  : 1.0.3
Release  : 2
URL      : https://rubygems.org/downloads/rails-deprecated_sanitizer-1.0.3.gem
Source0  : https://rubygems.org/downloads/rails-deprecated_sanitizer-1.0.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Rails::Deprecated::Sanitizer
In Rails 4.2 HTML sanitization has been rewritten using a more secure library.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rails-deprecated_sanitizer-1.0.3
gem spec %{SOURCE0} -l --ruby > rubygem-rails-deprecated_sanitizer.gemspec

%build
gem build rubygem-rails-deprecated_sanitizer.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rails-deprecated_sanitizer-1.0.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rails-deprecated_sanitizer-1.0.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/ActionView/Helpers/SanitizeHelper/ClassMethods/HTML/cdesc-HTML.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/ActionView/Helpers/SanitizeHelper/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/ActionView/Helpers/SanitizeHelper/cdesc-SanitizeHelper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/ActionView/Helpers/cdesc-Helpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/ActionView/cdesc-ActionView.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/CDATA/cdesc-CDATA.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Conditions/cdesc-Conditions.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/FullSanitizer/cdesc-FullSanitizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/FullSanitizer/process_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/FullSanitizer/sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/LinkSanitizer/cdesc-LinkSanitizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/LinkSanitizer/process_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/LinkSanitizer/sanitizeable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Node/cdesc-Node.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Sanitizer/cdesc-Sanitizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Sanitizer/process_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Sanitizer/sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Sanitizer/sanitizeable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Sanitizer/tokenize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Sanitizer/validate_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/InvalidSelectorError/cdesc-InvalidSelectorError.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/attribute_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/cdesc-Selector.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/for_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/for_id-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/next_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/next_selector-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/nth_child-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/only_child-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/select-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/select_first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Selector/simple_selector-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Tag/cdesc-Tag.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Tag/select-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Text/cdesc-Text.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Tokenizer/cdesc-Tokenizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/WhiteListSanitizer/cdesc-WhiteListSanitizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/WhiteListSanitizer/contains_bad_protocols%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/WhiteListSanitizer/process_attributes_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/WhiteListSanitizer/process_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/WhiteListSanitizer/sanitize_css-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/WhiteListSanitizer/tokenize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/cdesc-HTML.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/HTML/selector-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/Rails/DeprecatedSanitizer/Railtie/cdesc-Railtie.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/Rails/DeprecatedSanitizer/cdesc-DeprecatedSanitizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/Rails/DeprecatedSanitizer/full_sanitizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/Rails/DeprecatedSanitizer/link_sanitizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/Rails/DeprecatedSanitizer/white_list_sanitizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-deprecated_sanitizer-1.0.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails-deprecated_sanitizer.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/document.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/node.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/sanitizer.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/selector.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/tokenizer.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/railtie.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/test/cdata_node_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/test/deprecated_sanitizer_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/test/document_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/test/node_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/test/tag_node_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/test/text_node_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/test/tokenizer_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rails-deprecated_sanitizer-1.0.3.gemspec
