#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rails-deprecated_sanitizer
Version  : 1.0.3
Release  : 5
URL      : https://rubygems.org/downloads/rails-deprecated_sanitizer-1.0.3.gem
Source0  : https://rubygems.org/downloads/rails-deprecated_sanitizer-1.0.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Rails::Deprecated::Sanitizer
In Rails 4.2 HTML sanitization has been rewritten using a more secure library.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rails-deprecated_sanitizer-1.0.3
gem spec %{SOURCE0} -l --ruby > rubygem-rails-deprecated_sanitizer.gemspec

%build
gem build rubygem-rails-deprecated_sanitizer.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rails-deprecated_sanitizer-1.0.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rails-deprecated_sanitizer-1.0.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails-deprecated_sanitizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/sanitizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/tokenizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/html-scanner/html/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/lib/rails/deprecated_sanitizer/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/test/cdata_node_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/test/deprecated_sanitizer_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/test/document_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/test/node_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/test/tag_node_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/test/text_node_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-deprecated_sanitizer-1.0.3/test/tokenizer_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rails-deprecated_sanitizer-1.0.3.gemspec
